# Site settings
title: Sitong Liu
description: description
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sitong Liu
user_description: I'm a Graduate student in computer sicence and systems at University of Washington, I am currently looking for a Software Engineering Internship in summer 2020.
user_title: Master student in computer sicence and systems, University of Washington
email: liust97@outlook.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-152514956-1"

exclude: ['package.json', 'src' , 'node_modules']
